In [46]:
pip install pandas

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in .\.venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## pandas in Python

* A powerful Python library for data analysis and manipulation.
* Used to handle structured data like tables and spreadsheets.
* Provides two main data structures: **Series** and **DataFrame**.
* Helps in cleaning, filtering, sorting, and analyzing data easily.
* Widely used in Data Analytics, Machine Learning, and Data Science.

In [47]:
import os
import numpy as np
import pandas as pd

In [48]:
df = pd.read_csv(r"D:\OneDrive\data science\pandas\Used_Bikes.csv")

In [49]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [50]:
df.head()#by default 1st five rows pass krta h

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [51]:
df.head(10)#if we pass a value to utni rows deta h

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [52]:
df.tail()#by default last five rows deta h and if we pass a value to last utni rows deta h

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [53]:
df.info()# gives information about dataset

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [54]:
df.columns# gives all the columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [55]:
df["price"]#specific column

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [56]:
df[["brand"]]#more sturctured

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [57]:
df[['brand','price']]

               brand     price
0                TVS   35000.0
1      Royal Enfield  119900.0
2            Triumph  600000.0
3                TVS   65000.0
4             Yamaha   80000.0
...              ...       ...
32643           Hero   39000.0
32644            TVS   30000.0
32645          Bajaj   60000.0
32646           Hero   15600.0
32647          Bajaj   22000.0

[32648 rows x 2 columns]

In [58]:
df["brand"].unique()#kon konsi brand h

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [59]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [60]:
df["brand"].nunique()#no. of unique brands

23

In [61]:
df['brand'].value_counts()#har brand m kitni bikes h

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [62]:
#

In [63]:
df.duplicated()#duplicate values p true dega

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [64]:
df.duplicated().sum()

np.int64(25324)

In [65]:
df.drop_duplicates()#duplicate values ko drop kr dega

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [66]:
df.drop_duplicates(inplace=True)#duplicate values ko drop kr dega

In [67]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [68]:
df.isna()#missing values p true dega

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [69]:
df.isnull().sum()#null values p true dega

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [70]:
df.dropna(inplace=True)#missing values ko drop kr dega

In [71]:
#1st algo of ML
#linear equation 
#y = mx+c
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [72]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [73]:
owner_dict = {'First Owner': 1,'Second Owner': 2,'Third Owner': 3,'Fourth & Above Owner': 4}

In [74]:
df['owner']=df['owner'].map(owner_dict)

In [75]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1.0,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1.0,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1.0,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1.0,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1.0,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1.0,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1.0,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1.0,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1.0,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1.0,5.0,220.0,Bajaj

In [76]:
#df.drop('city',axis=1,inplace=True)#city column ko drop kr diya

In [ ]:
#df.drop(['city','bike_name'],axis=1,inplace=True)#city column ko drop kr diya

In [78]:
tvs_brand=df[df['brand']=='TVS']#

In [79]:
df

         price  kms_driven  owner  age  power            brand
0      35000.0     17654.0    1.0  3.0  110.0              TVS
1     119900.0     11000.0    1.0  4.0  350.0    Royal Enfield
2     600000.0       110.0    1.0  8.0  675.0          Triumph
3      65000.0     16329.0    1.0  4.0  180.0              TVS
4      80000.0     10000.0    1.0  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0    1.0  8.0  150.0             Hero
9369   35000.0     60000.0    1.0  9.0  220.0            Bajaj
9370  450000.0      3430.0    1.0  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0    1.0  4.0  400.0            Bajaj
9372   80000.0      7127.0    1.0  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [80]:
tvs_under2 = tvs_brand[tvs_brand['age']<=2]

In [81]:
tvs_under2[tvs_under2['kms_driven']<=20000]

         price  kms_driven  owner  age  power brand
193    85000.0     16000.0    1.0  2.0  160.0   TVS
360    78700.0      3710.0    1.0  2.0  160.0   TVS
401   108500.0     10000.0    1.0  2.0  200.0   TVS
425    87000.0      7000.0    1.0  2.0  160.0   TVS
511    85000.0      7000.0    1.0  2.0  160.0   TVS
594    91800.0      1050.0    1.0  2.0  160.0   TVS
664    89000.0      3000.0    1.0  2.0  160.0   TVS
1097   93500.0      2500.0    1.0  2.0  200.0   TVS
1126  130000.0      1300.0    1.0  1.0  200.0   TVS
1132   98000.0       749.0    1.0  1.0  160.0   TVS
1171  200000.0      4400.0    1.0  2.0  310.0   TVS
1318  125000.0       530.0    1.0  2.0  200.0   TVS
1514   76000.0      8000.0    1.0  2.0  160.0   TVS
1678  122000.0      3100.0    1.0  2.0  200.0   TVS
1712  224000.0      3900.0    1.0  2.0  310.0   TVS
1741   98500.0      2800.0    1.0  2.0  200.0   TVS
1762   89135.0      2800.0    1.0  2.0  160.0   TVS
1802   88000.0       900.0    1.0  2.0  180.0   TVS
2325   92000.0      4500.0    1.0  2.0  200.0   TVS
2360   54000.0      6000.0    1.0  2.0  110.0   TVS
2415   85000.0     11496.0    1.0  2.0  160.0   TVS
3071   94000.0       893.0    1.0  2.0  160.0   TVS
3333   85000.0      6821.0    1.0  2.0  160.0   TVS
3440   92000.0     14289.0    1.0  2.0  160.0   TVS
4251   51000.0     12000.0    1.0  2.0  110.0   TVS
4367   90000.0      2672.0    1.0  2.0  160.0   TVS
5506  106000.0      1890.0    1.0  2.0  200.0   TVS
5510   90000.0      3095.0    1.0  2.0  180.0   TVS
5557  102000.0      8120.0    1.0  2.0  200.0   TVS
5805  128000.0      4000.0    1.0  2.0  200.0   TVS
6003   90700.0       900.0    1.0  2.0  160.0   TVS
6058  220000.0      5432.0    1.0  2.0  310.0   TVS
6571   86000.0     15228.0    1.0  2.0  160.0   TVS
6787  106000.0      7157.0    1.0  2.0  200.0   TVS
7055   46000.0      6222.0    1.0  2.0  100.0   TVS
8883  120000.0      4442.0    1.0  2.0  200.0   TVS
9322   58000.0      4020.0    1.0  2.0  110.0   TVS

In [82]:
royal_brand=df[df['brand']=='Royal Enfield']

In [83]:
ROYAL_under2 = royal_brand[royal_brand['age']<=2]

In [84]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['price']<=150000)] #multiple conditions

         price  kms_driven  owner  age  power          brand
194   145000.0      4000.0    1.0  2.0  350.0  Royal Enfield
479   150000.0      4000.0    1.0  2.0  350.0  Royal Enfield
1006  148000.0      7300.0    1.0  2.0  350.0  Royal Enfield
1203  150000.0      1800.0    1.0  2.0  350.0  Royal Enfield
1681  135000.0      3800.0    1.0  2.0  350.0  Royal Enfield
1716  144700.0       770.0    1.0  2.0  350.0  Royal Enfield
1749  145000.0      5000.0    1.0  2.0  350.0  Royal Enfield
2982  137000.0      8400.0    1.0  2.0  350.0  Royal Enfield
5495  150000.0      1947.0    1.0  2.0  350.0  Royal Enfield
5939  105000.0      7255.0    1.0  2.0  350.0  Royal Enfield
6090  127000.0        83.0    1.0  2.0  350.0  Royal Enfield
6298  140000.0      2000.0    1.0  2.0  350.0  Royal Enfield
6329  130000.0      3688.0    1.0  2.0  350.0  Royal Enfield
6590  130000.0     19249.0    1.0  2.0  350.0  Royal Enfield
7019  135000.0     10779.0    1.0  2.0  350.0  Royal Enfield
7294  133500.0      1608.0    1.0  2.0  350.0  Royal Enfield
8192  145000.0     12400.0    1.0  2.0  350.0  Royal Enfield

In [85]:
df.query("brand=='Royal Enfield' and age<=2" )#same query in different way

         price  kms_driven  owner  age  power          brand
38    190500.0      4550.0    1.0  2.0  500.0  Royal Enfield
81    260000.0      3800.0    1.0  2.0  650.0  Royal Enfield
139   173300.0     14000.0    1.0  2.0  410.0  Royal Enfield
194   145000.0      4000.0    1.0  2.0  350.0  Royal Enfield
222   177982.0      7000.0    1.0  2.0  410.0  Royal Enfield
...        ...         ...    ...  ...    ...            ...
7294  133500.0      1608.0    1.0  2.0  350.0  Royal Enfield
7694  215000.0       417.0    1.0  2.0  500.0  Royal Enfield
8139  169000.0      4411.0    1.0  2.0  350.0  Royal Enfield
8192  145000.0     12400.0    1.0  2.0  350.0  Royal Enfield
8836  170200.0      1000.0    1.0  2.0  350.0  Royal Enfield

[61 rows x 6 columns]

In [86]:
df.drop(['bike_name'],axis=1,inplace=True)#drop column

KeyError: "['bike_name'] not found in axis"

In [ ]:
x=df.drop(['price'],axis=1)#drop column

            city  kms_driven        owner   age  power          brand
0      Ahmedabad     17654.0  First Owner   3.0  110.0            TVS
1          Delhi     11000.0  First Owner   4.0  350.0  Royal Enfield
2          Delhi       110.0  First Owner   8.0  675.0        Triumph
3      Bangalore     16329.0  First Owner   4.0  180.0            TVS
4      Bangalore     10000.0  First Owner   3.0  150.0         Yamaha
...          ...         ...          ...   ...    ...            ...
32643      Delhi     22000.0  First Owner   4.0  100.0           Hero
32644     Karnal      6639.0  First Owner   9.0  180.0            TVS
32645      Delhi     20373.0  First Owner   6.0  220.0          Bajaj
32646     Jaipur     84186.0  First Owner  16.0  125.0           Hero
32647       Pune     60857.0  First Owner  13.0  150.0          Bajaj

[32648 rows x 6 columns]

In [ ]:
y=df['price']#target variable

In [ ]:
y

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [ ]:
#df.to_csv("clean_bike_data.csv")#save as csv file #of clean data